name: "Backstage Catalog Info Helper"
description: "A GitHub Action to help with Backstage Catalog Info"
inputs:
  github-app-id:
    description: "The GitHub APP ID"
    required: true
  github-app-private-key:
    description: "The GitHub APP Private Key"
    required: true
  github-app-installation-id:
    description: "The GitHub APP Installation ID"
    required: true
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@vb4ffde65f46336ab88eb53be808477a3936bae11
    - name: impersonate Read ONLY GH App
      uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a
      id: generate_token
      with:
        app_id: ${{ inputs.github-app-id }}
        private_key: ${{ inputs.github-app-private-key }}
    - name: Setup Node.js
      uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d
      with:
        node-version: "20.x"
    - name: Run backstage catalog helper
      env:
        GITHUB_APP_ID: ${{ inputs.github-app-id }}
        GITHUB_APP_PRIVATE_KEY: ${{ inputs.github-app-private-key }}
        GITHUB_APP_INSTALLATION_ID: ${{ inputs.github-app-installation-id }}
      run: |
        node dist/index.js
      shell: bash
    - name: Create pull request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ steps.generate_token.outputs.token}}
        commit-message: 'Add catalog-info.yaml'
        branch: 'backstage/catalog-info'
        title: 'Add catalog-info.yaml'
        body: 'Add catalog-info.yaml'
        labels: 'backstage'
        changes: |
          add: |
            catalog-info.yaml
    
branding:
  icon: "file-text"
  color: "green"
