name: "Backstage Catalog Info Helper"
description: "A GitHub Action to help with Backstage Catalog Info"
inputs:
  github-app-id:
    description: "The GitHub APP ID"
    required: true
  github-app-private-key:
    description: "The GitHub APP Private Key"
    required: true
  github-organization:
    description: "The GitHub Organization"
    default: ${{ github.repository_owner }}
runs:
  using: node20
  main: "dist/index.js"
  
branding:
  icon: "file-text"
  color: "green"
