name: "Backstage Catalog Info Helper"
description: "A GitHub Action to help with Backstage Catalog Info"
inputs:
  github-app-id:
    description: "The GitHub APP ID"
    required: true
  github-app-private-key:
    description: "The GitHub APP Private Key"
    required: true
  github-app-installation-id:
    description: "The GitHub APP Installation ID"
    required: true
runs:
  using: composite
  steps:
    - run: echo "Hello World"
      shell: bash
    - run: echo ${{ inputs.github-app-id }}
      shell: bash
    - name: Setup Node.js
      uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d
      with:
        node-version: "20.x"
    - name: Run backstage catalog helper
      env:
        GITHUB_APP_ID: ${{ inputs.github-app-id }}
        GITHUB_APP_PRIVATE_KEY: ${{ inputs.github-app-private-key }}
        GITHUB_APP_INSTALLATION_ID: ${{ inputs.github-app-installation-id }}
      run: |
        node dist/index.js
      shell: bash
branding:
  icon: "file-text"
  color: "green"
