name: 'Backstage Catalog Info Helper'
description: 'A GitHub Action to help with Backstage Catalog Info'
inputs:
  github-app-id:
    description: 'The GitHub APP ID'
    required: true
  github-app-private-key:
    description: 'The GitHub APP Private Key'
    required: true
  github-app-installation-id:
    description: 'The GitHub APP Installation ID'
    required: true
# runs:
#   using: 'node20'
#   main: 'dist/index.js'
runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '20.x'
    - name: Install dependencies
      run: npm install
      shell: bash
    - name: Build
      run: npm run build
      shell: bash
    - name: Run helper
      run: node dist/index.js
      shell: bash
    - name: Upload Catalog Info
      uses: actions/upload-artifact@v2
      with:
        name: catalog-info
        path: catalog-info.yaml
    - name: Create PR
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'Update catalog-info.yaml'
        title: 'Update catalog-info.yaml'
        body: 'Update catalog-info.yaml'
        branch: 'update-catalog-info'
        branch-suffix: timestamp
        base: 'main'
        labels: 'catalog-info'
        draft: false
branding:
  icon: 'file-text'
  color: 'green'